USE Test_RTS_IntegraX;

-- Tabela: FX_categoria
INSERT INTO FX_categoria (nome, descricao) VALUES
('!Historico!','Histórico de antigos meios de armazenagem (sem histórico)'),
('Alimentaçao','Gastos com alimentação em geral'),
('Casa','Gastos relacionados à manutenção e suprimentos para o lar'),
('Compras pessoais','Gastos com roupas, calçados e acessórios'),
('Contas','Gastos com serviços essenciais (água, luz, telefone, internet, etc.)'),
('Creditos','Rendimentos recebidos através de créditos ou empréstimos'),
('Cuidados de saúde','Gastos com medicamentos, consultas e tratamentos de saúde'),
('Educação','Gastos com cursos, materiais escolares e capacitação'),
('Freelance','Rendimentos recebidos por trabalhos autônomos'),
('Hobbies e Lazer','Gastos com atividades de lazer e entretenimento'),
('Home Improvement','Gastos com reformas e melhorias no lar'),
('Impostos','Gastos com taxas e tributos governamentais'),
('Jogos','Gasto com jogos digitais, videogames etc..'),
('Não é uma despesa','Registros que não representam despesas (transferências internas, ajustes)'),
('Os encargos bancários','Taxas e tarifas cobradas por instituições financeiras'),
('Outros','Gastos diversos não categorizados'),
('Papelaria','Gastos com materiais de escritório e papelaria'),
('Pet Care','Gastos relacionados a cuidados com animais de estimação'),
('Planos','Assinaturas e planos digitais (streaming, apps, etc.)'),
('Presentes','Gastos com presentes e doações'),
('Renda / Juros','Rendimentos recebidos de aplicações financeiras'),
('Rendimento de Investimento','Lucros e dividendos de investimentos'),
('Retirar Dinheiro','Saques em espécie (não considerado despesa)'),
('Salário e Salário','Rendimentos recebidos através de salário'),
('Transferencias','Movimentações entre contas (não considerado despesa)'),
('Transporte','Gastos com locomoção (combustível, passagens, manutenção de veículos, etc.)'),
('Vestuário','Gastos com roupas, calçados e acessórios');



-- Tabela: FX_subcategoria
INSERT INTO FX_subcategoria (nome, categoria_id, descricao) VALUES
('!Historico!',1,'Aquelas compras do mês que sempre esquece o principal e traz 10 pacotes de biscoito kkk'),
('Alimentaçao',2,'Aquela categoria que todo mundo acha que controla, mas no fim é só um monte de "ah, foi barato" somado kkk'),
('Almoço',2,'Aquele restaurante caro que você só vai "de vez em quando", mas tá lá toda semana no extrato kkk'),
('Compra do mes',2,'Quando você prometeu fazer dieta, mas o carrinho do mercado tá 80% besteira e 20% arroz kkk'),
('lanches',2,'"Só um salgadinho" que vira um banquete de meia-noite e depois culpa no app de finanças kkk'),
('Mercado',2,'Aquela compra "rápida" que sempre inclui um item de R$50 que você nem sabia que existia kkk'),
('Casa',3,'Conta de luz, conserto da torneira e aquela decoração que prometeu fazer mas tá encostada desde 2022 kkk'),
('Terreno',3,'Aquela parcela do terreno "que vai valorizar", mas por enquanto só valoriza o estresse kkk'),
('Compras pessoais',4,'"Eu mereço" transformado em boleto parcelado em 12x kkk'),
('Shoppe',4,'Compra "necessária" que você descobriu que existia 5 minutos antes de clicar no "comprar" kkk'),
('Contas',5,'Plano de telefone que promete internet ilimitada, mas no 5º dia do mês já tá acabando kkk'),
('Água e Esgoto',5,'A conta que vem com o bônus do "uso consciente" (tradução: a gente cobrou mais mesmo) kkk'),
('Cartao de credito',5,'"Aquele pagamento mínimo que é tipo um band-aid num buraco de bala de canhão" 💸 kkk'),
('Celular',5,'Plano de internet que promete "ilimitado" mas no 3º dia já tá mais lento que carroça na lama 🐌 kkk'),
('Serviço de On-line/Internet',5,'internet  "300MB/s" que na prática é buffer até pra ver um story do Instagram kkk'),
('Creditos',6,'Dinheiro que caiu do céu (ou do Nubank) e some em 2 segundos kkk'),
('Pagamento de fatura',6,'"Paguei o total! (mentira, foi só o mínimo e tô fingindo que não vi os juros)" 😅 kkk'),
('Cuidados de saúde',7,'Aquela consulta que você marca 3 vezes e cancela porque "tá caro demais" kkk'),
('Cabelo',7,'Corte "simples" que sai como se você tivesse financiado um apartamento kkk'),
('Dental',7,'O momento que você descobre que seu sorriso vale mais que seu carro kkk'),
('Remedio',7,'Farmácia virando segunda casa e você já tem desconto de frequentador kkk'),
('Educação',8,'Matrícula, provas, certificados e aqueles boletos que aparecem do nada da faculdade kkk'),
('Taxas',8,'"Taxa administrativa" que na prática é "a gente quer mais dinheiro mesmo" kkk'),
('Freelance',9,'Quando você vira a própria empresa e descobre que seu chefe é um cuzao (e é você mesmo) kkk'),
('Carpinagem no Alan',9,'Serviço feito por amor (ou por falta de opção no mercado) kkk'),
('Hobbies e Lazer',10,'Tudo que você gasta e depois fala "mas é investimento em qualidade de vida" pra se sentir melhor kkk'),
('Bar',10,'"Só uma cervejinha" que vira rodada, petisco e conta de 3 dígitos kkk'),
('Cerveja',10,'Água que custa o preço de um ouro líquido e você paga feliz kkk'),
('Cinema e Video Rentals',10,'Pipoca que custa mais que o ingresso e você compra igual um trouxa kkk'),
('Entreterimento',10,'Streaming que você assina pra ver 1 série e esquece de cancelar kkk'),
('Final de semana',10,'48 horas que consomem 80% do seu salário kkk'),
('happy hour',10,'"Vou só tomar uma" que vira jantar, Uber premium e arrependimento no dia seguinte kkk'),
('Home Improvement',11,'Reforma que começou R$500 e terminou num empréstimo consignado kkk'),
('Impostos',12,'Quando o governo faz a festa com seu dinheiro e você nem foi convidado kkk'),
('Jogos',13,'"Só mais um loot box" que vira o equivalente a uma prestação de um Fiat Uno kkk'),
('Console',13,'Parcela do videogame que você comprou pra "relaxar" (e agora trabalha mais pra pagar) kkk'),
('Valorant',13,'Skin que não melhora seu aim, mas pelo menos você morre estiloso kkk'),
('Não é uma despesa',14,'Transferência entre contas que você faz 5x e ainda se perde kkk'),
('Os encargos bancários',15,'Taxas que aparecem do nada e o banco chama de "mimos" kkk'),
('Investimento',15,'Dinheiro que você coloca pra render e só vê render o banco kkk'),
('Taxa de Serviço',15,'"Manutenção de conta" que na prática é "a gente cobra porque pode" kkk'),
('Outros',16,'Aquela despesa que não encaixa em lugar nenhum (e nem você quer lembrar) kkk'),
('Familhao',16,'Familhão do Luciano HULK que ainda vai me deixar rico'),
('Papelaria',17,'Caneta que você comprou por R$50 e jurou que ia "mudar sua produtividade" kkk'),
('Xerox',17,'Cópia que custa mais que o original e você paga porque "precisa" kkk'),
('Pet Care',18,'Bichinho que come melhor que você e ainda tem plano de saúde kkk'),
('Alimentos',18,'Ração gourmet que seu pet nem liga, mas você compra porque "ele merece" kkk'),
('Suprimentos',18,'Brinquedo que custa R$120 e dura 3 minutos antes de virar destroços kkk'),
('Planos',19,'Assinaturas que você nem usa mas fica com medo de cancelar kkk'),
('google one',19,'Espaço na nuvem que você paga pra guardar 500 screenshots inúteis kkk'),
('Netflix',19,'Plataforma que você assina pra ver 1 série e fica rolando catálogo sem achar nada kkk'),
('Presentes',20,'Aquele presente caro que você compra pra alguém que nem lembra seu aniversário kkk'),
('Renda / Juros',21,'Dinheiro que cai sem você fazer nada (sonho? não, só extrato errado mesmo) kkk'),
('Rendimento de Investimento',22,'Quando seu dinheiro trabalha mais que você (mas só nos seus cálculos otimistas) kkk'),
('Renda Fixa',22,'Investimento "seguro" que rende menos que a inflação do pão de queijo kkk'),
('Retirar Dinheiro',23,'Saque que você faz "pra emergência" e gasta com besteira no mesmo dia kkk'),
('Salário e Salário',24,'Aquela grana que entra e some em 2 dias pagando contas que você nem lembrava kkk'),
('Adiantamento',24,'Dinheiro que você recebe antecipado e some antes mesmo de cair na conta kkk'),
('Beneficio',24,'VR que você gasta em 3 dias e passa o resto do mês comendo pão com ovo kkk'),
('Bonus',24,'"Presente" da empresa que basicamente é seu próprio dinheiro devolvido kkk'),
('Decimo Terceiro',24,'Dinheiro que você já contou 10x antes de receber e some em 24h kkk'),
('Horas extras',24,'Quando você vende sua alma por um pouco mais no fim do mês kkk'),
('Plantao',24,'Plantão que você faz pensando no dinheiro e no fim gasta tudo em delivery kkk'),
('Salario',24,'Aquela felicidade que dura exatamente até abrir o app do banco kkk'),
('Transferencias',25,'Dinheiro que vai de uma conta pra outra e some no buraco negro das finanças kkk'),
('Amigos',25,'"Me paga depois" que vira "me esquece depois" kkk'),
('Outros',25,'Transferência misteriosa que nem você sabe de onde veio kkk'),
('Pais',25,'Aquele dinheiro que você devolve (ou não) e vira assunto de toda reunião familiar kkk'),
('Transporte',26,'Tudo que você gasta pra se locomover e ainda chegar atrasado kkk'),
('Documentos',26,'CNH que custa um rim e você ainda tem que renovar todo ano kkk'),
('Estacionamento',26,'Lugar que você paga pra deixar o carro e ainda sai com multa kkk'),
('Gasolina',26,'Combustível que aumenta toda vez que seu tanque tá vazio kkk'),
('Manutenção',26,'"Revisão simples" que vira lista de 20 itens "urgentes" kkk'),
('Pagamento de carro',26,'Parcela do carro que você comprou pra "facilitar a vida" kkk'),
('Passagen',26,'Ônibus que atrasa, avião que cancela, e você pagando por tudo kkk'),
('Uber',26,'Corrida que custa o dobro em horário de pico, mas a gente paga pra não pegar ônibus lotado kkk'),
('Vestuário',27,'Roupa que você compra pra "ocasiões especiais" e acaba usando pra ficar em casa kkk'),
('Bazar',27,'Pechincha que você acha que fez, mas no fim pagou caro igual kkk'),
('Cartao de loja',27,'Parcela de roupa que você nem lembra mais, mas tá lá no extrato kkk');


-- Tabela: FX_conta
INSERT INTO FX_conta (nome, descricao, tipo, status_id) VALUES
('PicPay', 'Conta do PicPay', 'Debito', 9),
('Santader', 'Conta do Santader', 'Debito', 12),
('Nubank', 'Conta do Nubank', 'Debito', 13),
('Neon', 'Conta do Neon', 'Debito', 12),
('Itau', 'Conta do Itau', 'Debito', 12),
('Pagbank', 'Conta do Pagbank', 'Debito', 9),
('Inter', 'Conta do Inter', 'Debito', 10),
('C6', 'Conta do C6 Bank', 'Debito', 12),
('Bradesco', 'Conta do Bradesco', 'Debito', 9),
('Next', 'Conta do Next', 'Debito', 10),
('Rico', 'Conta da Rico', 'Debito', 12);